### ISSUE TITLE
OpenCL implementations have issues when increasing the problem size

### ISSUE THREAD

**Issue by sergisiso** [stfc/PSycloneBench#28]
Both the manual version and the psyclone-generated version of JITed OpenCL run correctly for sizes up to 512x512:

```
Implementation		Compiler	Arch	ua checksum	uv checksum	time/step
psykal_serial:          gnu		cpu	0.26305978E+02	0.28550284E+03	0.48535E-01	
psykal_omp:             gnu		cpu	0.26305978E+02	0.28550284E+03	0.17252E-01	
psykal_dm:              gnu		cpu	0.26305978E+02	0.28550284E+03	0.13927E-01
psykal_opencl           gnu+jit(intel)  cpu     0.26305978E+02  0.28550284E+03  0.39982E-01
psykal_opencl           gnu+jit(nvidia) gpu     0.26305978E+02  0.28550284E+03  0.79914E-01 
```

But for bigger tests cases:
- the Intel driver version starts to segfault
- the nvidia version gives a `Hit error: clEnqueueReadBuffer: CL_OUT_OF_RESOURCES`.

Doing a back-of-the-envelope calculation for the 13 double precision fields on the timestep it should take a 1000x1000 problem ~1000x1000x8x13 = 100 Mbytes. So memory is not the issue and there is probably another resource that the current OpenCL implementation is abusing.

**Comment by arporter** [comment]
Looking back at my notes, my OpenCL version failed on NVIDIA for problem sizes of 512 and 1024. I don't think I ever investigated the cause. I did tune the workgroup size for performance, especially for the momentum kernels. For 255x255 the time/step was 4.35E-04s on a K20c.

**Comment by sergisiso** [comment]
This is the naive OpenCL on my GTX1060 mid-range gaming(reduced DP units?) gpu, so I am already happy that the performance is in the ballpark of the other versions.

Besides looking at the resources issue, I intent to write 2 more time_step_mod_x.f90 versions like in the serial implementation folder:
- 1 with workgroups (I can already auto-generate this with PSyclone)
- 1 with OpenCL tasks instead of NDRanges.
and see how each architecture behaves with the different styles of OpenCL.

**Comment by sergisiso** [comment]
Closing this issue. The problem was fixed by allowing to set the alignment environment variable for OpenCL < 1.2 and the OpenCL kernels having the boundary values as an argument.
