### ISSUE TITLE
Update NemoLite2D C OpenCL manual implementation to use a C PSy layer

### ISSUE THREAD

**Issue by sergisiso** [stfc/PSycloneBench#33]
When the Fortran->iso_c_wrapper->C Psy layer implementation is on master, the 'single_file_c_opencl' implementations can be brought to use this same structure. This will mean to remove the logic that copies the infrastructure and move the opencl initialization (now in `main()`) into a `if(first_time)` block in the C PSy-layer. I think this has the following advantages:
- There has been a few changes to the infrastructure, build system, kernels ... which may have broken it, it will be good to make sure it is up to date (e.g. are the `if(jj == 0)return;` conditions inside kernels still needed?).
- It will be easier to check the correctness and keep it up to date in the future as it will share more infrastructure with the rest.
- Some of the optimizations for FPGA (EuroEXA) like using `clEnqueueKernels` and `channels` are much easier to implement here first that updating the FortCL library (some are already started in 'single_file_c_opencl'). So for a better comparison it will be good the rest of the code as similar as possible to the baseline (current PSyclone-generated OpenCL)

@arporter Do you think this is a good idea? and do you see something that would make this refactor not feasible?

**Comment by arporter** [comment]
That sounds good to me. If it's going to be useful for optimising in EuroEXA *and* this will mean that it has more code in common with the other benchmarks then it's worth doing.
