### ISSUE TITLE
Use dl_esm_inf infrastructure

### ISSUE THREAD

**Issue by arporter** [stfc/PSycloneBench#8]
Currently PSycloneBench comes with its own infrastructure code. This has now been put into https://github.com/stfc/dl_esm_inf and therefore we should use that here.

**Comment by arporter** [comment]
I've re-structured the directories in preparation for bringing in a second, NEMO-based benchmark (currently in NEMO-DSL).

**Comment by rupertford** [comment]
Merged to master in PR #9
