### ISSUE TITLE
Add OpenMP offload target for the tracer advection benchmark

### ISSUE THREAD

**Issue by arporter** [stfc/PSycloneBench#86]
We want to demonstrate OpenMP offload for the PSyclone paper and thus it makes sense to add it here. I'll work off `PSyclone/examples/nemo/eg1` for this.

**Comment by arporter** [comment]
@sergisiso do you have the necessary compiler flags for the NVIDIA compiler to hand?

**Comment by sergisiso** [comment]
This are already in the repo in https://github.com/stfc/PSycloneBench/blob/master/compiler_setup/nvidia.sh you also need the "-gpu=managed" if using managed memory.

**Comment by sergisiso** [comment]
Also note that the script in eg1 will need some changes due to the new range2loop+hoist_bounds+hoist bound statements in order to provide good GPU performance. If you want I can take this after your initial PR and check/update the script while I am introducing the changes in the transformations.

**Comment by arporter** [comment]
Thanks @sergisiso. I just need to test what I have on Glados or Isambard now.

**Comment by arporter** [comment]
`Makefile_gen` adds OMPFLAGS to F90FLAGS so we have to unset it when building for OMP offload. I need to document this in the README.
